apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudplusai
  namespace: cloudplusai
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: cloudplusai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudplusai-backend
                port:
                  number: 5000
